/*
 * Container for all of the games global variables
 * */

package  
{
	import flash.filters.BlurFilter;
	import net.bloom.BloomLighting;
	import net.blur.BlurCanvas;
	import net.flashpunk.Entity;
	import net.flashpunk.FP;
	import net.flashpunk.graphics.Image;
	import net.flashpunk.World;
	import worlds.*;
	
	
	public class GV extends Entity
	{
		public static var WORLD:Array = new Array; //stores all of the level tiles, generated by GameWorld
		public static var CURRENT_LEVEL:Level; //the currently loaded world tile
		public static var PLAYER:Player; //the player
		public static var INVENTORY:Array = new Array();
		public static var EQUIPPED_WEAPON:Entity = null;
		
		public static var BLUR_CANVAS:BlurCanvas = new BlurCanvas(GC.CURSOR_BLUR_LEVEL);
		public static var ITEM_BLOOM_LIGHTING:BloomLighting = new BloomLighting(GC.BLOOM_AMOUNT, GC.BLOOM_QUALITY);
		
		/*
		 * Returns reference to this object by matching the name
		 * */
		public static function getLevelByName(name:String):Object
		{
			for each( var level:Level in WORLD )
			{
				if (level.levelName == name) return level;
			}
			FP.console.log('Unable to load level ' + name);
			return null;
		}
	}
}